export * from './rootComment.controller'
export * from './rootComment.model'
export * from './rootComment.routes'
export * from './rootComment.service'
export * from './rootComment.types'
export * from './rootComment.validation'
